/**
 * GRI Standards disclosures (2021 Universal + Topic Standards).
 *
 * The crosswalk to canonical metrics is the single most-used in practice:
 * BRSR Principle 6 disclosures align almost 1:1 with GRI 302/303/305/306.
 */

export type GriResponseType = "NUMERIC" | "TEXT" | "BOOLEAN" | "TABLE" | "PERCENTAGE";

export interface GriDisclosure {
  /** Stable GRI code: e.g. "GRI 302-1". */
  section_id: string;
  /** Standard code: 1, 2, 3, 302, 303, 305, 306, 401, 403, 404, 405, 308, 414. */
  standard: number;
  standard_name: string;
  disclosure_number: string;
  question_text: string;
  response_type: GriResponseType;
  unit?: string;
  is_mandatory: boolean;
  mapped_canonical_keys: string[];
  formula: string | null;
  narrative_template: string | null;
}

function g(p: GriDisclosure): GriDisclosure {
  return p;
}

const UNIVERSAL: GriDisclosure[] = [
  g({
    section_id: "GRI 2-1",
    standard: 2,
    standard_name: "General Disclosures 2021",
    disclosure_number: "2-1",
    question_text: "Organisational details.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 2-7",
    standard: 2,
    standard_name: "General Disclosures 2021",
    disclosure_number: "2-7",
    question_text: "Employees - total number, by gender and region.",
    response_type: "TABLE",
    unit: "count",
    is_mandatory: true,
    mapped_canonical_keys: [
      "employee_count_total",
      "employee_count_male",
      "employee_count_female",
      "employee_count_perm",
      "employee_count_temp",
    ],
    formula: "m.employee_count_total",
    narrative_template:
      "Total employees: {{metric.employee_count_total}} ({{metric.employee_count_male}} male; {{metric.employee_count_female}} female).",
  }),
  g({
    section_id: "GRI 2-8",
    standard: 2,
    standard_name: "General Disclosures 2021",
    disclosure_number: "2-8",
    question_text: "Workers who are not employees.",
    response_type: "NUMERIC",
    unit: "count",
    is_mandatory: true,
    mapped_canonical_keys: ["employee_count_contract"],
    formula: "m.employee_count_contract",
    narrative_template: null,
  }),
  g({
    section_id: "GRI 2-9",
    standard: 2,
    standard_name: "General Disclosures 2021",
    disclosure_number: "2-9",
    question_text: "Governance structure and composition.",
    response_type: "TABLE",
    is_mandatory: true,
    mapped_canonical_keys: ["board_size", "independent_directors_count", "women_directors_count"],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 2-27",
    standard: 2,
    standard_name: "General Disclosures 2021",
    disclosure_number: "2-27",
    question_text: "Compliance with laws and regulations.",
    response_type: "TABLE",
    is_mandatory: true,
    mapped_canonical_keys: ["regulatory_actions_count", "fines_paid_inr"],
    formula: "m.fines_paid_inr",
    narrative_template: null,
  }),
  g({
    section_id: "GRI 3-1",
    standard: 3,
    standard_name: "Material Topics 2021",
    disclosure_number: "3-1",
    question_text: "Process to determine material topics.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 3-2",
    standard: 3,
    standard_name: "Material Topics 2021",
    disclosure_number: "3-2",
    question_text: "List of material topics.",
    response_type: "TABLE",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 3-3",
    standard: 3,
    standard_name: "Material Topics 2021",
    disclosure_number: "3-3",
    question_text: "Management of material topics.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
];

const ENERGY: GriDisclosure[] = [
  g({
    section_id: "GRI 302-1",
    standard: 302,
    standard_name: "Energy 2016",
    disclosure_number: "302-1",
    question_text: "Energy consumption within the organisation (renewable + non-renewable, electricity, heating, cooling, steam).",
    response_type: "TABLE",
    unit: "gj",
    is_mandatory: true,
    mapped_canonical_keys: [
      "electricity_kwh",
      "electricity_from_renewable_kwh",
      "electricity_from_grid_kwh",
      "diesel_l",
      "petrol_l",
      "lpg_kg",
      "lng_kg",
      "png_scm",
      "coal_tonnes",
      "biomass_tonnes",
      "steam_purchased_gj",
      "total_energy_consumed_gj",
    ],
    formula: "m.total_energy_consumed_gj",
    narrative_template:
      "Total energy consumed within the organisation: {{metric.total_energy_consumed_gj}} GJ. Renewable share: {{metric.electricity_from_renewable_kwh}} kWh of the total.",
  }),
  g({
    section_id: "GRI 302-2",
    standard: 302,
    standard_name: "Energy 2016",
    disclosure_number: "302-2",
    question_text: "Energy consumption outside of the organisation.",
    response_type: "NUMERIC",
    unit: "gj",
    is_mandatory: false,
    mapped_canonical_keys: ["scope3_cat3_tco2e", "scope3_cat4_tco2e", "scope3_cat6_tco2e", "scope3_cat7_tco2e"],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 302-3",
    standard: 302,
    standard_name: "Energy 2016",
    disclosure_number: "302-3",
    question_text: "Energy intensity.",
    response_type: "NUMERIC",
    unit: "gj_per_inr_crore",
    is_mandatory: false,
    mapped_canonical_keys: ["energy_intensity_per_revenue", "energy_intensity_per_employee"],
    formula: "m.energy_intensity_per_revenue",
    narrative_template:
      "Energy intensity: {{metric.energy_intensity_per_revenue}} GJ per INR Crore revenue.",
  }),
  g({
    section_id: "GRI 302-4",
    standard: 302,
    standard_name: "Energy 2016",
    disclosure_number: "302-4",
    question_text: "Reduction of energy consumption.",
    response_type: "NUMERIC",
    unit: "gj",
    is_mandatory: false,
    mapped_canonical_keys: ["total_energy_consumed_gj"],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 302-5",
    standard: 302,
    standard_name: "Energy 2016",
    disclosure_number: "302-5",
    question_text: "Reductions in energy requirements of products and services.",
    response_type: "TEXT",
    is_mandatory: false,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
];

const WATER: GriDisclosure[] = [
  g({
    section_id: "GRI 303-1",
    standard: 303,
    standard_name: "Water and Effluents 2018",
    disclosure_number: "303-1",
    question_text: "Interactions with water as a shared resource.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 303-2",
    standard: 303,
    standard_name: "Water and Effluents 2018",
    disclosure_number: "303-2",
    question_text: "Management of water discharge-related impacts.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: ["water_discharged_kl"],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 303-3",
    standard: 303,
    standard_name: "Water and Effluents 2018",
    disclosure_number: "303-3",
    question_text: "Water withdrawal by source (surface, ground, seawater, produced, third-party).",
    response_type: "TABLE",
    unit: "kl",
    is_mandatory: true,
    mapped_canonical_keys: [
      "water_withdrawn_kl_groundwater",
      "water_withdrawn_kl_surface",
      "water_withdrawn_kl_third_party",
      "water_withdrawn_kl_seawater",
      "water_withdrawn_kl_produced",
      "water_withdrawn_total_kl",
    ],
    formula: "m.water_withdrawn_total_kl",
    narrative_template:
      "Water withdrawal: {{metric.water_withdrawn_total_kl}} KL (ground {{metric.water_withdrawn_kl_groundwater}}, surface {{metric.water_withdrawn_kl_surface}}, third-party {{metric.water_withdrawn_kl_third_party}}).",
  }),
  g({
    section_id: "GRI 303-4",
    standard: 303,
    standard_name: "Water and Effluents 2018",
    disclosure_number: "303-4",
    question_text: "Water discharge by destination, treatment level and priority substances.",
    response_type: "TABLE",
    unit: "kl",
    is_mandatory: true,
    mapped_canonical_keys: ["water_discharged_kl"],
    formula: "m.water_discharged_kl",
    narrative_template: null,
  }),
  g({
    section_id: "GRI 303-5",
    standard: 303,
    standard_name: "Water and Effluents 2018",
    disclosure_number: "303-5",
    question_text: "Water consumption.",
    response_type: "NUMERIC",
    unit: "kl",
    is_mandatory: true,
    mapped_canonical_keys: ["water_consumed_kl", "water_recycled_kl", "water_intensity_per_revenue"],
    formula: "m.water_consumed_kl",
    narrative_template:
      "Water consumption: {{metric.water_consumed_kl}} KL. Water recycled: {{metric.water_recycled_kl}} KL.",
  }),
];

const EMISSIONS: GriDisclosure[] = [
  g({
    section_id: "GRI 305-1",
    standard: 305,
    standard_name: "Emissions 2016",
    disclosure_number: "305-1",
    question_text: "Direct (Scope 1) GHG emissions.",
    response_type: "NUMERIC",
    unit: "tco2e",
    is_mandatory: true,
    mapped_canonical_keys: [
      "scope1_total_tco2e",
      "scope1_stationary_tco2e",
      "scope1_mobile_tco2e",
      "scope1_process_tco2e",
      "scope1_fugitive_tco2e",
    ],
    formula: "m.scope1_total_tco2e",
    narrative_template:
      "Scope 1 emissions: {{metric.scope1_total_tco2e}} tCO2e (stationary {{metric.scope1_stationary_tco2e}}, mobile {{metric.scope1_mobile_tco2e}}, process {{metric.scope1_process_tco2e}}, fugitive {{metric.scope1_fugitive_tco2e}}).",
  }),
  g({
    section_id: "GRI 305-2",
    standard: 305,
    standard_name: "Emissions 2016",
    disclosure_number: "305-2",
    question_text: "Energy indirect (Scope 2) GHG emissions (location-based and market-based).",
    response_type: "TABLE",
    unit: "tco2e",
    is_mandatory: true,
    mapped_canonical_keys: ["scope2_location_tco2e", "scope2_market_tco2e"],
    formula: "m.scope2_location_tco2e",
    narrative_template:
      "Scope 2 emissions: location-based {{metric.scope2_location_tco2e}} tCO2e; market-based {{metric.scope2_market_tco2e}} tCO2e.",
  }),
  g({
    section_id: "GRI 305-3",
    standard: 305,
    standard_name: "Emissions 2016",
    disclosure_number: "305-3",
    question_text: "Other indirect (Scope 3) GHG emissions by category.",
    response_type: "TABLE",
    unit: "tco2e",
    is_mandatory: false,
    mapped_canonical_keys: Array.from({ length: 15 }, (_, i) => `scope3_cat${i + 1}_tco2e`),
    formula: Array.from({ length: 15 }, (_, i) => `m.scope3_cat${i + 1}_tco2e`).join(" + "),
    narrative_template:
      "Scope 3 emissions across all 15 categories: {{calc.scope3_total}} tCO2e.",
  }),
  g({
    section_id: "GRI 305-4",
    standard: 305,
    standard_name: "Emissions 2016",
    disclosure_number: "305-4",
    question_text: "GHG emissions intensity.",
    response_type: "NUMERIC",
    unit: "tco2e_per_inr_crore",
    is_mandatory: false,
    mapped_canonical_keys: ["ghg_intensity_per_revenue", "ghg_intensity_per_unit_output"],
    formula: "m.ghg_intensity_per_revenue",
    narrative_template: null,
  }),
  g({
    section_id: "GRI 305-5",
    standard: 305,
    standard_name: "Emissions 2016",
    disclosure_number: "305-5",
    question_text: "Reduction of GHG emissions.",
    response_type: "NUMERIC",
    unit: "tco2e",
    is_mandatory: false,
    mapped_canonical_keys: ["scope1_total_tco2e", "scope2_location_tco2e"],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 305-6",
    standard: 305,
    standard_name: "Emissions 2016",
    disclosure_number: "305-6",
    question_text: "Emissions of ozone-depleting substances (ODS).",
    response_type: "NUMERIC",
    unit: "kg",
    is_mandatory: false,
    mapped_canonical_keys: ["ods_kg"],
    formula: "m.ods_kg",
    narrative_template: null,
  }),
  g({
    section_id: "GRI 305-7",
    standard: 305,
    standard_name: "Emissions 2016",
    disclosure_number: "305-7",
    question_text: "NOx, SOx, and other significant air emissions.",
    response_type: "TABLE",
    unit: "kg",
    is_mandatory: true,
    mapped_canonical_keys: ["nox_kg", "sox_kg", "pm_kg", "voc_kg"],
    formula: "m.nox_kg + m.sox_kg + m.pm_kg + m.voc_kg",
    narrative_template:
      "Air emissions other than GHG: NOx {{metric.nox_kg}} kg; SOx {{metric.sox_kg}} kg; PM {{metric.pm_kg}} kg; VOC {{metric.voc_kg}} kg.",
  }),
];

const WASTE: GriDisclosure[] = [
  g({
    section_id: "GRI 306-1",
    standard: 306,
    standard_name: "Waste 2020",
    disclosure_number: "306-1",
    question_text: "Waste generation and significant waste-related impacts.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 306-2",
    standard: 306,
    standard_name: "Waste 2020",
    disclosure_number: "306-2",
    question_text: "Management of significant waste-related impacts.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 306-3",
    standard: 306,
    standard_name: "Waste 2020",
    disclosure_number: "306-3",
    question_text: "Waste generated.",
    response_type: "TABLE",
    unit: "kg",
    is_mandatory: true,
    mapped_canonical_keys: [
      "waste_hazardous_kg",
      "waste_non_hazardous_kg",
      "e_waste_kg",
      "plastic_waste_kg",
      "biomedical_waste_kg",
      "battery_waste_kg",
      "radioactive_waste_kg",
      "other_waste_kg",
    ],
    formula:
      "m.waste_hazardous_kg + m.waste_non_hazardous_kg + m.e_waste_kg + m.plastic_waste_kg + m.biomedical_waste_kg + m.battery_waste_kg + m.radioactive_waste_kg + m.other_waste_kg",
    narrative_template:
      "Total waste generated: hazardous {{metric.waste_hazardous_kg}} kg; non-hazardous {{metric.waste_non_hazardous_kg}} kg.",
  }),
  g({
    section_id: "GRI 306-4",
    standard: 306,
    standard_name: "Waste 2020",
    disclosure_number: "306-4",
    question_text: "Waste diverted from disposal (recycling, reuse).",
    response_type: "NUMERIC",
    unit: "kg",
    is_mandatory: true,
    mapped_canonical_keys: ["waste_recycled_kg"],
    formula: "m.waste_recycled_kg",
    narrative_template: null,
  }),
  g({
    section_id: "GRI 306-5",
    standard: 306,
    standard_name: "Waste 2020",
    disclosure_number: "306-5",
    question_text: "Waste directed to disposal (landfill, incineration).",
    response_type: "TABLE",
    unit: "kg",
    is_mandatory: true,
    mapped_canonical_keys: ["waste_to_landfill_kg", "waste_to_incineration_kg"],
    formula: "m.waste_to_landfill_kg + m.waste_to_incineration_kg",
    narrative_template: null,
  }),
];

const EMPLOYMENT: GriDisclosure[] = [
  g({
    section_id: "GRI 401-1",
    standard: 401,
    standard_name: "Employment 2016",
    disclosure_number: "401-1",
    question_text: "New employee hires and employee turnover, by age group and gender.",
    response_type: "TABLE",
    unit: "count",
    is_mandatory: true,
    mapped_canonical_keys: ["employee_new_hires", "employee_turnover"],
    formula: "m.employee_new_hires + m.employee_turnover",
    narrative_template:
      "New hires: {{metric.employee_new_hires}}; exits: {{metric.employee_turnover}}.",
  }),
  g({
    section_id: "GRI 401-2",
    standard: 401,
    standard_name: "Employment 2016",
    disclosure_number: "401-2",
    question_text: "Benefits provided to full-time employees not provided to temporary or part-time employees.",
    response_type: "TEXT",
    is_mandatory: false,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 401-3",
    standard: 401,
    standard_name: "Employment 2016",
    disclosure_number: "401-3",
    question_text: "Parental leave.",
    response_type: "TABLE",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
];

const HEALTH_SAFETY: GriDisclosure[] = [
  g({
    section_id: "GRI 403-1",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-1",
    question_text: "Occupational health and safety management system.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 403-2",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-2",
    question_text: "Hazard identification, risk assessment, and incident investigation.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: ["near_miss_count"],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 403-3",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-3",
    question_text: "Occupational health services.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 403-4",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-4",
    question_text: "Worker participation, consultation, and communication on OH&S.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 403-5",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-5",
    question_text: "Worker training on occupational health and safety.",
    response_type: "PERCENTAGE",
    unit: "pct",
    is_mandatory: true,
    mapped_canonical_keys: ["safety_training_coverage_pct", "training_hours_ehs"],
    formula: "m.safety_training_coverage_pct",
    narrative_template: null,
  }),
  g({
    section_id: "GRI 403-6",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-6",
    question_text: "Promotion of worker health.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 403-7",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-7",
    question_text: "Prevention and mitigation of OH&S impacts directly linked by business relationships.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 403-8",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-8",
    question_text: "Workers covered by an occupational health and safety management system.",
    response_type: "PERCENTAGE",
    unit: "pct",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 403-9",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-9",
    question_text: "Work-related injuries (rates and number).",
    response_type: "TABLE",
    unit: "count",
    is_mandatory: true,
    mapped_canonical_keys: [
      "ltifr",
      "trifr",
      "fatality_count_employees",
      "fatality_count_contractors",
    ],
    formula: "m.fatality_count_employees + m.fatality_count_contractors",
    narrative_template:
      "LTIFR {{metric.ltifr}}; TRIFR {{metric.trifr}}; fatalities (employees {{metric.fatality_count_employees}}, contractors {{metric.fatality_count_contractors}}).",
  }),
  g({
    section_id: "GRI 403-10",
    standard: 403,
    standard_name: "Occupational Health and Safety 2018",
    disclosure_number: "403-10",
    question_text: "Work-related ill health.",
    response_type: "NUMERIC",
    unit: "count",
    is_mandatory: true,
    mapped_canonical_keys: ["occupational_disease_cases"],
    formula: "m.occupational_disease_cases",
    narrative_template: null,
  }),
];

const TRAINING: GriDisclosure[] = [
  g({
    section_id: "GRI 404-1",
    standard: 404,
    standard_name: "Training and Education 2016",
    disclosure_number: "404-1",
    question_text: "Average hours of training per year per employee, by gender and employee category.",
    response_type: "NUMERIC",
    unit: "hours_per_employee",
    is_mandatory: true,
    mapped_canonical_keys: ["training_hours_per_employee", "training_hours_total"],
    formula: "m.training_hours_per_employee",
    narrative_template:
      "Average training hours per employee: {{metric.training_hours_per_employee}}.",
  }),
  g({
    section_id: "GRI 404-2",
    standard: 404,
    standard_name: "Training and Education 2016",
    disclosure_number: "404-2",
    question_text: "Programmes for upgrading employee skills and transition assistance programmes.",
    response_type: "TEXT",
    is_mandatory: false,
    mapped_canonical_keys: ["training_hours_skill"],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 404-3",
    standard: 404,
    standard_name: "Training and Education 2016",
    disclosure_number: "404-3",
    question_text: "Percentage of employees receiving regular performance and career development reviews.",
    response_type: "PERCENTAGE",
    unit: "pct",
    is_mandatory: true,
    mapped_canonical_keys: ["training_coverage_pct"],
    formula: "m.training_coverage_pct",
    narrative_template: null,
  }),
];

const DIVERSITY: GriDisclosure[] = [
  g({
    section_id: "GRI 405-1",
    standard: 405,
    standard_name: "Diversity and Equal Opportunity 2016",
    disclosure_number: "405-1",
    question_text: "Diversity of governance bodies and employees.",
    response_type: "TABLE",
    is_mandatory: true,
    mapped_canonical_keys: [
      "women_in_workforce_pct",
      "women_in_management_pct",
      "women_on_board_pct",
      "pwd_in_workforce_pct",
      "employee_count_by_age_bracket",
    ],
    formula: "m.women_in_workforce_pct",
    narrative_template:
      "Women in workforce: {{metric.women_in_workforce_pct}}%; in management: {{metric.women_in_management_pct}}%; on board: {{metric.women_on_board_pct}}%.",
  }),
  g({
    section_id: "GRI 405-2",
    standard: 405,
    standard_name: "Diversity and Equal Opportunity 2016",
    disclosure_number: "405-2",
    question_text: "Ratio of basic salary and remuneration of women to men.",
    response_type: "NUMERIC",
    unit: "ratio",
    is_mandatory: true,
    mapped_canonical_keys: ["gender_pay_gap_pct", "median_remuneration_male", "median_remuneration_female"],
    formula: "m.median_remuneration_female / m.median_remuneration_male",
    narrative_template:
      "Female-to-male median remuneration ratio: {{calc.gender_pay_ratio}}. Gender pay gap: {{metric.gender_pay_gap_pct}}%.",
  }),
];

const SUPPLY_CHAIN: GriDisclosure[] = [
  g({
    section_id: "GRI 308-1",
    standard: 308,
    standard_name: "Supplier Environmental Assessment 2016",
    disclosure_number: "308-1",
    question_text: "New suppliers screened using environmental criteria.",
    response_type: "PERCENTAGE",
    unit: "pct",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 308-2",
    standard: 308,
    standard_name: "Supplier Environmental Assessment 2016",
    disclosure_number: "308-2",
    question_text: "Negative environmental impacts in the supply chain and actions taken.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 414-1",
    standard: 414,
    standard_name: "Supplier Social Assessment 2016",
    disclosure_number: "414-1",
    question_text: "New suppliers screened using social criteria.",
    response_type: "PERCENTAGE",
    unit: "pct",
    is_mandatory: true,
    mapped_canonical_keys: [],
    formula: null,
    narrative_template: null,
  }),
  g({
    section_id: "GRI 414-2",
    standard: 414,
    standard_name: "Supplier Social Assessment 2016",
    disclosure_number: "414-2",
    question_text: "Negative social impacts in the supply chain and actions taken.",
    response_type: "TEXT",
    is_mandatory: true,
    mapped_canonical_keys: ["child_labour_incidents", "forced_labour_incidents"],
    formula: null,
    narrative_template: null,
  }),
];

export const GRI_DISCLOSURES: GriDisclosure[] = [
  ...UNIVERSAL,
  ...ENERGY,
  ...WATER,
  ...EMISSIONS,
  ...WASTE,
  ...EMPLOYMENT,
  ...HEALTH_SAFETY,
  ...TRAINING,
  ...DIVERSITY,
  ...SUPPLY_CHAIN,
];

export function getGriByStandard(standard: number): GriDisclosure[] {
  return GRI_DISCLOSURES.filter((d) => d.standard === standard);
}
