/**
 * Canonical ESG metric registry.
 *
 * This is the SINGLE source of truth for what an ESG number IS in the BRSR-v2
 * platform. Framework definitions (BRSR, GRI, SASB, TCFD, IFRS, ESRS, CDP) all
 * cross-walk back to keys defined here.
 *
 * Adding a metric:
 *  - choose a stable snake_case key (it goes into the database and never changes)
 *  - set canonical_unit (the unit stored in the warehouse — convert at the edge)
 *  - list allowed_units that the AI extractor / UI may accept
 *  - declare allowed dimensions (period, scope_node, gas, fuel_type, country, state, ...)
 *  - declare aggregation_rule so roll-ups across periods/nodes are deterministic
 *  - for GHG metrics, declare gwp_basis (which IPCC report) and boundary_tag
 *  - provide aliases for AI extraction so the extractor can recognise synonyms
 */

export type AggregationRule =
  | "sum" // sums across child nodes & periods
  | "avg" // mean
  | "weighted_avg" // weighted by a paired count metric
  | "last" // most recent value wins (e.g. headcount snapshots)
  | "max"
  | "min"
  | "ratio" // numerator/denominator restated each period — never sum
  | "bool_any"; // true if any child is true

export type MetricCategory = "environment" | "social" | "governance";

export type DataQualityTier =
  | 1 // measured directly, audited
  | 2 // measured, internally checked
  | 3 // calculated from primary activity data (e.g. fuel L x factor)
  | 4; // estimated / proxied / industry average

export type GwpBasis = "AR5" | "AR6_100" | "AR6_20" | "AR4";

export type GhgBoundaryTag =
  | "scope1_stationary"
  | "scope1_mobile"
  | "scope1_process"
  | "scope1_fugitive"
  | "scope2_location"
  | "scope2_market"
  | `scope3_cat${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15}`
  | "biogenic"
  | "out_of_scope";

export type DimensionKey =
  | "period"
  | "scope_node"
  | "gas"
  | "fuel_type"
  | "vehicle_type"
  | "country"
  | "state"
  | "grid_region"
  | "facility"
  | "gender"
  | "age_bracket"
  | "employment_type"
  | "disability_status"
  | "ses_category"
  | "sector"
  | "supplier_tier"
  | "product_line"
  | "channel"
  | "currency"
  | "source_category"
  | "discharge_destination";

export interface ValueConstraints {
  /** Inclusive lower bound. Use 0 for non-negative quantities. */
  min?: number;
  /** Inclusive upper bound. Use 100 for percentages. */
  max?: number;
  /** Stored data type. `int` rejects fractional input from the extractor. */
  dtype: "int" | "float" | "bool" | "string";
}

export interface CanonicalMetric {
  /** Stable snake_case ID. Goes into the warehouse and never changes. */
  key: string;
  /** Human-readable label for UI. */
  name: string;
  /** One-sentence description; used in tooltips and as RAG context for the AI. */
  description: string;
  /** Canonical storage unit (what lives in the warehouse). */
  canonical_unit: string;
  /** Units the AI extractor / UI may accept; conversion happens on ingest. */
  allowed_units: string[];
  category: MetricCategory;
  subcategory: string;
  dimensions: DimensionKey[];
  aggregation_rule: AggregationRule;
  /** For GHG metrics, which inventory boundary this metric belongs to. */
  boundary_tag?: GhgBoundaryTag;
  /** Which IPCC GWP table to use when converting non-CO2 gases to CO2e. */
  gwp_basis?: GwpBasis;
  /** Best-case quality tier achievable for this metric (used in scoring). */
  data_quality_tier: DataQualityTier;
  value_constraints: ValueConstraints;
  /** Synonyms the AI extractor should recognise. Lowercase, no punctuation. */
  aliases: string[];
  /** Registry schema version (bumped when shape changes). */
  version: number;
  /** ISO date this definition becomes valid. */
  valid_from: string;
}

const NON_NEGATIVE_FLOAT: ValueConstraints = { min: 0, dtype: "float" };
const PERCENTAGE: ValueConstraints = { min: 0, max: 100, dtype: "float" };
const NON_NEGATIVE_INT: ValueConstraints = { min: 0, dtype: "int" };
const BOOLEAN: ValueConstraints = { dtype: "bool" };

function m(p: Omit<CanonicalMetric, "version" | "valid_from">): CanonicalMetric {
  return { ...p, version: 1, valid_from: "2024-04-01" };
}

// ---------------------------------------------------------------------------
// ENVIRONMENT — Energy
// ---------------------------------------------------------------------------

const ENERGY: CanonicalMetric[] = [
  m({
    key: "electricity_kwh",
    name: "Electricity consumed",
    description: "Total electrical energy consumed across all sources (grid + on-site renewable + on-site fossil generation).",
    canonical_unit: "kwh",
    allowed_units: ["kwh", "mwh", "gwh", "gj", "mj"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility", "state"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["electricity consumption", "power consumed", "electricity used", "kwh consumed", "electricity drawn"],
  }),
  m({
    key: "electricity_from_renewable_kwh",
    name: "Renewable electricity consumed",
    description: "Electricity sourced from renewable sources (on-site solar/wind, PPAs, I-RECs).",
    canonical_unit: "kwh",
    allowed_units: ["kwh", "mwh", "gwh"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility", "source_category"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["renewable electricity", "green power", "solar consumed", "wind consumed", "rec backed electricity"],
  }),
  m({
    key: "electricity_from_grid_kwh",
    name: "Grid electricity consumed",
    description: "Electricity purchased from the grid (location-based).",
    canonical_unit: "kwh",
    allowed_units: ["kwh", "mwh", "gwh"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility", "grid_region", "state"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["grid electricity", "purchased electricity", "utility power", "discom electricity"],
  }),
  m({
    key: "diesel_l",
    name: "Diesel consumed",
    description: "Volume of diesel consumed in stationary and mobile combustion sources.",
    canonical_unit: "l",
    allowed_units: ["l", "kl", "gal_us", "gal_uk"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility", "fuel_type"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["hsd", "high speed diesel", "diesel fuel", "diesel litres"],
  }),
  m({
    key: "petrol_l",
    name: "Petrol consumed",
    description: "Volume of petrol/gasoline consumed in mobile combustion sources.",
    canonical_unit: "l",
    allowed_units: ["l", "kl", "gal_us"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["gasoline", "ms", "motor spirit", "petrol fuel"],
  }),
  m({
    key: "lpg_kg",
    name: "LPG consumed",
    description: "Liquefied petroleum gas consumed for stationary combustion (heating, cooking, process).",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes", "cylinder_14_2kg", "cylinder_19kg"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["liquefied petroleum gas", "cooking gas", "propane", "butane"],
  }),
  m({
    key: "lng_kg",
    name: "LNG consumed",
    description: "Liquefied natural gas consumed.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes", "scm"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["liquefied natural gas"],
  }),
  m({
    key: "png_scm",
    name: "Piped natural gas consumed",
    description: "PNG consumed via pipeline, in standard cubic metres.",
    canonical_unit: "scm",
    allowed_units: ["scm", "nm3", "mmbtu", "kwh"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["piped natural gas", "natural gas pipeline", "city gas", "png"],
  }),
  m({
    key: "coal_tonnes",
    name: "Coal consumed",
    description: "Coal consumed for stationary combustion (boilers, captive power).",
    canonical_unit: "tonnes",
    allowed_units: ["tonnes", "kg"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility", "fuel_type"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["coal usage", "thermal coal", "lignite", "bituminous coal"],
  }),
  m({
    key: "biomass_tonnes",
    name: "Biomass consumed",
    description: "Solid biomass (woodchips, husks, pellets) consumed for combustion. Reported as biogenic.",
    canonical_unit: "tonnes",
    allowed_units: ["tonnes", "kg"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    boundary_tag: "biogenic",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["biofuel", "husk", "wood chips", "agri residue", "briquette"],
  }),
  m({
    key: "steam_purchased_gj",
    name: "Steam purchased",
    description: "Thermal energy purchased as steam.",
    canonical_unit: "gj",
    allowed_units: ["gj", "mj", "kwh", "mmbtu", "tonnes_steam"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["purchased steam", "external steam"],
  }),
  m({
    key: "total_energy_consumed_gj",
    name: "Total energy consumed",
    description: "Sum of all fuels + electricity + steam, converted to GJ. Derived metric.",
    canonical_unit: "gj",
    allowed_units: ["gj", "tj", "kwh", "mwh"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["total energy", "total energy consumption", "energy consumed"],
  }),
  m({
    key: "energy_intensity_per_revenue",
    name: "Energy intensity per revenue",
    description: "Total energy GJ / revenue INR. Restated each period.",
    canonical_unit: "gj_per_inr_crore",
    allowed_units: ["gj_per_inr_crore", "gj_per_usd_million"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["energy intensity", "energy per revenue"],
  }),
  m({
    key: "energy_intensity_per_employee",
    name: "Energy intensity per employee",
    description: "Total energy GJ / headcount.",
    canonical_unit: "gj_per_employee",
    allowed_units: ["gj_per_employee", "kwh_per_employee"],
    category: "environment",
    subcategory: "energy",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["energy per employee", "per capita energy"],
  }),
];

// ---------------------------------------------------------------------------
// ENVIRONMENT — Water
// ---------------------------------------------------------------------------

const WATER: CanonicalMetric[] = [
  m({
    key: "water_withdrawn_kl_groundwater",
    name: "Groundwater withdrawn",
    description: "Volume of water withdrawn from groundwater sources (boreholes, wells).",
    canonical_unit: "kl",
    allowed_units: ["kl", "ml", "m3", "l"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["ground water", "borewell", "well water"],
  }),
  m({
    key: "water_withdrawn_kl_surface",
    name: "Surface water withdrawn",
    description: "Volume of water withdrawn from surface sources (rivers, lakes, rainwater capture).",
    canonical_unit: "kl",
    allowed_units: ["kl", "ml", "m3"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["river water", "lake water", "surface water"],
  }),
  m({
    key: "water_withdrawn_kl_third_party",
    name: "Third-party water withdrawn",
    description: "Water purchased from municipalities or water utilities.",
    canonical_unit: "kl",
    allowed_units: ["kl", "ml", "m3"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["municipal water", "purchased water", "tanker water"],
  }),
  m({
    key: "water_withdrawn_kl_seawater",
    name: "Seawater withdrawn",
    description: "Volume of seawater withdrawn (cooling, desalination feed).",
    canonical_unit: "kl",
    allowed_units: ["kl", "ml", "m3"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["sea water", "marine water"],
  }),
  m({
    key: "water_withdrawn_kl_produced",
    name: "Produced water",
    description: "Water that comes up as a by-product of operations (e.g. mining, O&G).",
    canonical_unit: "kl",
    allowed_units: ["kl", "ml", "m3"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["process water", "mine water", "associated water"],
  }),
  m({
    key: "water_withdrawn_total_kl",
    name: "Total water withdrawn",
    description: "Sum of all withdrawal sources.",
    canonical_unit: "kl",
    allowed_units: ["kl", "ml", "m3"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["total water withdrawal", "gross water"],
  }),
  m({
    key: "water_discharged_kl",
    name: "Water discharged",
    description: "Volume of water discharged to any destination after use.",
    canonical_unit: "kl",
    allowed_units: ["kl", "ml", "m3"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node", "discharge_destination"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["water discharge", "effluent discharged", "wastewater discharged"],
  }),
  m({
    key: "water_consumed_kl",
    name: "Water consumed",
    description: "Water withdrawn minus discharged (i.e. evaporated/embedded in product).",
    canonical_unit: "kl",
    allowed_units: ["kl", "ml", "m3"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["water consumption", "net water use"],
  }),
  m({
    key: "water_recycled_kl",
    name: "Water recycled / reused",
    description: "Volume of treated wastewater recycled back into processes.",
    canonical_unit: "kl",
    allowed_units: ["kl", "ml", "m3"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["recycled water", "reused water", "ztl water"],
  }),
  m({
    key: "water_intensity_per_revenue",
    name: "Water intensity per revenue",
    description: "Water withdrawn / revenue.",
    canonical_unit: "kl_per_inr_crore",
    allowed_units: ["kl_per_inr_crore", "kl_per_usd_million"],
    category: "environment",
    subcategory: "water",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["water intensity"],
  }),
];

// ---------------------------------------------------------------------------
// ENVIRONMENT — Waste
// ---------------------------------------------------------------------------

const WASTE: CanonicalMetric[] = [
  m({
    key: "waste_hazardous_kg",
    name: "Hazardous waste generated",
    description: "Hazardous waste generated, per Schedule I of Hazardous Waste Rules 2016.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["haz waste", "schedule I waste", "hw"],
  }),
  m({
    key: "waste_non_hazardous_kg",
    name: "Non-hazardous waste generated",
    description: "Non-hazardous solid waste generated.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["non hazardous waste", "general waste", "msw"],
  }),
  m({
    key: "waste_recycled_kg",
    name: "Waste recycled",
    description: "Waste diverted to recycling.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["recycled waste", "recovered waste"],
  }),
  m({
    key: "waste_to_landfill_kg",
    name: "Waste sent to landfill",
    description: "Waste disposed in landfills.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["landfilled", "dumped", "land disposal"],
  }),
  m({
    key: "waste_to_incineration_kg",
    name: "Waste incinerated",
    description: "Waste incinerated (with or without energy recovery).",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["incinerated waste", "burnt waste"],
  }),
  m({
    key: "e_waste_kg",
    name: "E-waste generated",
    description: "Electronic waste generated, per E-Waste Management Rules 2022.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["electronic waste", "weee", "ewaste"],
  }),
  m({
    key: "plastic_waste_kg",
    name: "Plastic waste generated",
    description: "Plastic waste generated, per Plastic Waste Management Rules 2016.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["plastic packaging", "single use plastic", "pwm"],
  }),
  m({
    key: "biomedical_waste_kg",
    name: "Biomedical waste generated",
    description: "Biomedical waste, per Bio-Medical Waste Management Rules 2016.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["biomedical", "medical waste", "bmw"],
  }),
  m({
    key: "battery_waste_kg",
    name: "Battery waste generated",
    description: "Battery waste, per Battery Waste Management Rules 2022.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["used batteries", "battery scrap"],
  }),
  m({
    key: "radioactive_waste_kg",
    name: "Radioactive waste generated",
    description: "Radioactive waste, per AERB regulations.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["radioactive", "nuclear waste"],
  }),
  m({
    key: "other_waste_kg",
    name: "Other waste generated",
    description: "Other waste streams not captured by specific categories.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "waste",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["miscellaneous waste"],
  }),
];

// ---------------------------------------------------------------------------
// ENVIRONMENT — GHG
// ---------------------------------------------------------------------------

const GHG: CanonicalMetric[] = [
  m({
    key: "scope1_total_tco2e",
    name: "Scope 1 GHG emissions (total)",
    description: "Direct GHG emissions from owned/controlled sources.",
    canonical_unit: "tco2e",
    allowed_units: ["tco2e", "kgco2e", "mtco2e"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node", "facility", "gas"],
    aggregation_rule: "sum",
    boundary_tag: "scope1_stationary",
    gwp_basis: "AR6_100",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["scope 1", "direct emissions", "scope1"],
  }),
  m({
    key: "scope1_stationary_tco2e",
    name: "Scope 1 - stationary combustion",
    description: "Direct emissions from stationary combustion (boilers, furnaces, captive power).",
    canonical_unit: "tco2e",
    allowed_units: ["tco2e", "kgco2e"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node", "facility", "fuel_type"],
    aggregation_rule: "sum",
    boundary_tag: "scope1_stationary",
    gwp_basis: "AR6_100",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["stationary combustion", "boiler emissions"],
  }),
  m({
    key: "scope1_mobile_tco2e",
    name: "Scope 1 - mobile combustion",
    description: "Direct emissions from mobile sources (owned fleet, forklifts).",
    canonical_unit: "tco2e",
    allowed_units: ["tco2e", "kgco2e"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node", "vehicle_type"],
    aggregation_rule: "sum",
    boundary_tag: "scope1_mobile",
    gwp_basis: "AR6_100",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["mobile combustion", "fleet emissions", "vehicle emissions"],
  }),
  m({
    key: "scope1_process_tco2e",
    name: "Scope 1 - process emissions",
    description: "Direct emissions from chemical/physical processes (cement calcination, ammonia, steel).",
    canonical_unit: "tco2e",
    allowed_units: ["tco2e", "kgco2e"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    boundary_tag: "scope1_process",
    gwp_basis: "AR6_100",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["process emissions", "industrial process emissions"],
  }),
  m({
    key: "scope1_fugitive_tco2e",
    name: "Scope 1 - fugitive emissions",
    description: "Direct emissions from leaks (refrigerants, SF6, methane leaks).",
    canonical_unit: "tco2e",
    allowed_units: ["tco2e", "kgco2e"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node", "gas"],
    aggregation_rule: "sum",
    boundary_tag: "scope1_fugitive",
    gwp_basis: "AR6_100",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["fugitive emissions", "refrigerant leak", "sf6 leak"],
  }),
  m({
    key: "scope2_location_tco2e",
    name: "Scope 2 - location-based",
    description: "Indirect emissions from purchased electricity using grid average factor.",
    canonical_unit: "tco2e",
    allowed_units: ["tco2e", "kgco2e"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node", "grid_region"],
    aggregation_rule: "sum",
    boundary_tag: "scope2_location",
    gwp_basis: "AR6_100",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["scope 2 location", "location based scope 2"],
  }),
  m({
    key: "scope2_market_tco2e",
    name: "Scope 2 - market-based",
    description: "Indirect emissions from purchased electricity using contract instruments (PPAs, RECs).",
    canonical_unit: "tco2e",
    allowed_units: ["tco2e", "kgco2e"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    boundary_tag: "scope2_market",
    gwp_basis: "AR6_100",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["scope 2 market", "market based scope 2"],
  }),
];

// Scope 3 cat 1..15 generated as a block
const SCOPE3_CATS: { n: number; name: string; alias: string[] }[] = [
  { n: 1, name: "Purchased goods and services", alias: ["purchased goods", "supplier emissions"] },
  { n: 2, name: "Capital goods", alias: ["capital goods", "capex emissions"] },
  { n: 3, name: "Fuel- and energy-related activities", alias: ["upstream fuel", "well to tank"] },
  { n: 4, name: "Upstream transportation and distribution", alias: ["upstream logistics", "inbound transport"] },
  { n: 5, name: "Waste generated in operations", alias: ["waste disposal emissions"] },
  { n: 6, name: "Business travel", alias: ["business travel", "flights emissions"] },
  { n: 7, name: "Employee commuting", alias: ["employee commute"] },
  { n: 8, name: "Upstream leased assets", alias: ["leased assets upstream"] },
  { n: 9, name: "Downstream transportation and distribution", alias: ["outbound logistics", "downstream transport"] },
  { n: 10, name: "Processing of sold products", alias: ["processing sold products"] },
  { n: 11, name: "Use of sold products", alias: ["product use phase"] },
  { n: 12, name: "End-of-life of sold products", alias: ["end of life products"] },
  { n: 13, name: "Downstream leased assets", alias: ["leased assets downstream"] },
  { n: 14, name: "Franchises", alias: ["franchises"] },
  { n: 15, name: "Investments", alias: ["financed emissions", "pcaf"] },
];

const SCOPE3: CanonicalMetric[] = SCOPE3_CATS.map((c) =>
  m({
    key: `scope3_cat${c.n}_tco2e`,
    name: `Scope 3 cat ${c.n} - ${c.name}`,
    description: `GHG Protocol Scope 3 Category ${c.n}: ${c.name}.`,
    canonical_unit: "tco2e",
    allowed_units: ["tco2e", "kgco2e"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    boundary_tag: `scope3_cat${c.n}` as GhgBoundaryTag,
    gwp_basis: "AR6_100",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: c.alias,
  })
);

const GHG_INTENSITY: CanonicalMetric[] = [
  m({
    key: "ghg_intensity_per_revenue",
    name: "GHG intensity per revenue",
    description: "Scope 1+2 / revenue.",
    canonical_unit: "tco2e_per_inr_crore",
    allowed_units: ["tco2e_per_inr_crore", "tco2e_per_usd_million"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["ghg intensity revenue", "emissions intensity"],
  }),
  m({
    key: "ghg_intensity_per_unit_output",
    name: "GHG intensity per unit output",
    description: "Scope 1+2 / physical production unit (tonne, MWh, etc.).",
    canonical_unit: "tco2e_per_unit",
    allowed_units: ["tco2e_per_tonne", "tco2e_per_mwh", "kgco2e_per_unit"],
    category: "environment",
    subcategory: "ghg",
    dimensions: ["period", "scope_node", "product_line"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["emissions per unit", "ghg per output"],
  }),
];

// ---------------------------------------------------------------------------
// ENVIRONMENT — Air, Biodiversity, Materials
// ---------------------------------------------------------------------------

const AIR: CanonicalMetric[] = [
  m({
    key: "nox_kg",
    name: "NOx emissions",
    description: "Nitrogen oxides emitted to air.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "air",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["nox", "nitrogen oxides", "no2"],
  }),
  m({
    key: "sox_kg",
    name: "SOx emissions",
    description: "Sulphur oxides emitted to air.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "air",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["sox", "sulphur oxides", "so2"],
  }),
  m({
    key: "pm_kg",
    name: "Particulate matter emissions",
    description: "Particulate matter (PM2.5 + PM10) emitted to air.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "air",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["particulate matter", "pm", "pm10", "pm2.5", "dust"],
  }),
  m({
    key: "voc_kg",
    name: "VOC emissions",
    description: "Volatile organic compounds emitted to air.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "air",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["volatile organic compounds", "vocs"],
  }),
  m({
    key: "ods_kg",
    name: "Ozone-depleting substances",
    description: "ODS emissions, expressed in CFC-11 equivalent.",
    canonical_unit: "kg",
    allowed_units: ["kg", "tonnes"],
    category: "environment",
    subcategory: "air",
    dimensions: ["period", "scope_node", "gas"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["ods", "ozone depleting substances", "cfc"],
  }),
];

const BIODIVERSITY: CanonicalMetric[] = [
  m({
    key: "protected_area_sqkm",
    name: "Operations in protected areas",
    description: "Total land of operations within or adjacent to protected areas.",
    canonical_unit: "sqkm",
    allowed_units: ["sqkm", "ha", "acre"],
    category: "environment",
    subcategory: "biodiversity",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["protected areas", "ecologically sensitive area"],
  }),
  m({
    key: "land_disturbed_ha",
    name: "Land disturbed",
    description: "Total area of land disturbed by operations during the period.",
    canonical_unit: "ha",
    allowed_units: ["ha", "sqkm", "acre"],
    category: "environment",
    subcategory: "biodiversity",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["land disturbance", "land use change"],
  }),
  m({
    key: "land_restored_ha",
    name: "Land restored / rehabilitated",
    description: "Area of land restored to natural or productive use.",
    canonical_unit: "ha",
    allowed_units: ["ha", "sqkm"],
    category: "environment",
    subcategory: "biodiversity",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["land rehabilitation", "reforested area", "afforestation"],
  }),
];

const MATERIALS: CanonicalMetric[] = [
  m({
    key: "virgin_materials_tonnes",
    name: "Virgin materials consumed",
    description: "Materials extracted from primary sources used as inputs.",
    canonical_unit: "tonnes",
    allowed_units: ["tonnes", "kg"],
    category: "environment",
    subcategory: "materials",
    dimensions: ["period", "scope_node", "product_line"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["virgin materials", "primary materials"],
  }),
  m({
    key: "recycled_materials_tonnes",
    name: "Recycled materials consumed",
    description: "Materials sourced from recycled/secondary inputs.",
    canonical_unit: "tonnes",
    allowed_units: ["tonnes", "kg"],
    category: "environment",
    subcategory: "materials",
    dimensions: ["period", "scope_node", "product_line"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["recycled inputs", "post consumer recycled"],
  }),
  m({
    key: "renewable_materials_tonnes",
    name: "Renewable materials consumed",
    description: "Bio-based / renewable raw materials used.",
    canonical_unit: "tonnes",
    allowed_units: ["tonnes", "kg"],
    category: "environment",
    subcategory: "materials",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["bio based materials", "renewable inputs"],
  }),
];

// ---------------------------------------------------------------------------
// SOCIAL — Workforce, Diversity, Compensation
// ---------------------------------------------------------------------------

const WORKFORCE: CanonicalMetric[] = [
  m({
    key: "employee_count_total",
    name: "Total employees",
    description: "Headcount of permanent employees at period end.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["total employees", "total headcount", "total workforce"],
  }),
  m({
    key: "employee_count_male",
    name: "Male employees",
    description: "Male permanent employees at period end.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["male employees", "men employees"],
  }),
  m({
    key: "employee_count_female",
    name: "Female employees",
    description: "Female permanent employees at period end.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["female employees", "women employees"],
  }),
  m({
    key: "employee_count_lgbtq",
    name: "LGBTQ+ employees",
    description: "Employees self-identifying as LGBTQ+. Voluntary disclosure.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "last",
    data_quality_tier: 3,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["lgbtq employees", "lgbt employees"],
  }),
  m({
    key: "employee_count_pwd",
    name: "Employees with disabilities",
    description: "Employees with disabilities (PwD) at period end.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "disability_status"],
    aggregation_rule: "last",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["pwd", "differently abled", "persons with disabilities"],
  }),
  m({
    key: "employee_count_perm",
    name: "Permanent employees",
    description: "Headcount on permanent rolls.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["permanent employees", "regular employees"],
  }),
  m({
    key: "employee_count_temp",
    name: "Temporary / fixed-term employees",
    description: "Employees on temporary contracts.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["temporary employees", "fixed term workers"],
  }),
  m({
    key: "employee_count_contract",
    name: "Contract workers",
    description: "Non-employee workforce engaged via contractors.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "last",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["contract workers", "contractor headcount", "outsourced workforce"],
  }),
  m({
    key: "employee_count_by_age_bracket",
    name: "Employees by age bracket",
    description: "Headcount broken down by age bracket (under_30, 30_to_50, over_50).",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "age_bracket"],
    aggregation_rule: "last",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["age distribution", "employees by age"],
  }),
  m({
    key: "employee_new_hires",
    name: "New employees hired",
    description: "Employees joining during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "gender", "age_bracket"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["new hires", "joiners", "hires during period"],
  }),
  m({
    key: "employee_turnover",
    name: "Employees leaving",
    description: "Employees exiting during the period (voluntary + involuntary).",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["attrition", "exits", "leavers"],
  }),
];

const DIVERSITY: CanonicalMetric[] = [
  m({
    key: "women_in_workforce_pct",
    name: "Women in workforce (%)",
    description: "Female employees / total employees x 100.",
    canonical_unit: "pct",
    allowed_units: ["pct", "ratio"],
    category: "social",
    subcategory: "diversity",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["women percentage", "female ratio"],
  }),
  m({
    key: "women_in_management_pct",
    name: "Women in management (%)",
    description: "Female employees in management roles / total management.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "diversity",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["women in management", "female managers"],
  }),
  m({
    key: "women_on_board_pct",
    name: "Women on board (%)",
    description: "Female directors / total board size.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "ratio",
    data_quality_tier: 1,
    value_constraints: PERCENTAGE,
    aliases: ["women on board", "female board members"],
  }),
  m({
    key: "lgbtq_in_workforce_pct",
    name: "LGBTQ+ in workforce (%)",
    description: "LGBTQ+ self-identification rate.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "diversity",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 3,
    value_constraints: PERCENTAGE,
    aliases: ["lgbtq percentage"],
  }),
  m({
    key: "pwd_in_workforce_pct",
    name: "PwD in workforce (%)",
    description: "Employees with disabilities / total employees.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "diversity",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["pwd percentage", "disability ratio"],
  }),
];

const COMPENSATION: CanonicalMetric[] = [
  m({
    key: "median_remuneration_male",
    name: "Median remuneration - male",
    description: "Median annual remuneration of male employees.",
    canonical_unit: "inr",
    allowed_units: ["inr", "inr_lakh", "inr_crore", "usd"],
    category: "social",
    subcategory: "compensation",
    dimensions: ["period", "scope_node", "employment_type"],
    aggregation_rule: "weighted_avg",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["male median pay", "median salary male"],
  }),
  m({
    key: "median_remuneration_female",
    name: "Median remuneration - female",
    description: "Median annual remuneration of female employees.",
    canonical_unit: "inr",
    allowed_units: ["inr", "inr_lakh", "inr_crore", "usd"],
    category: "social",
    subcategory: "compensation",
    dimensions: ["period", "scope_node", "employment_type"],
    aggregation_rule: "weighted_avg",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["female median pay", "median salary female"],
  }),
  m({
    key: "gender_pay_gap_pct",
    name: "Gender pay gap (%)",
    description: "(Male median - Female median) / Male median x 100.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "compensation",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: { min: -100, max: 100, dtype: "float" },
    aliases: ["pay gap", "gender wage gap"],
  }),
  m({
    key: "ceo_to_worker_pay_ratio",
    name: "CEO to median worker pay ratio",
    description: "CEO total compensation / median employee compensation.",
    canonical_unit: "ratio",
    allowed_units: ["ratio"],
    category: "governance",
    subcategory: "compensation",
    dimensions: ["period"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["ceo pay ratio", "pay multiple"],
  }),
];

// ---------------------------------------------------------------------------
// SOCIAL — Training, H&S, Human Rights, Community, Customer
// ---------------------------------------------------------------------------

const TRAINING: CanonicalMetric[] = [
  m({
    key: "training_hours_total",
    name: "Total training hours",
    description: "Total hours of employee training delivered.",
    canonical_unit: "hours",
    allowed_units: ["hours", "person_hours"],
    category: "social",
    subcategory: "training",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["training hours", "learning hours"],
  }),
  m({
    key: "training_hours_ehs",
    name: "EHS training hours",
    description: "Training hours specifically related to environment, health & safety.",
    canonical_unit: "hours",
    allowed_units: ["hours"],
    category: "social",
    subcategory: "training",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["safety training", "ehs training"],
  }),
  m({
    key: "training_hours_skill",
    name: "Skill upgradation training hours",
    description: "Training hours on technical / skill upgradation.",
    canonical_unit: "hours",
    allowed_units: ["hours"],
    category: "social",
    subcategory: "training",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["skill training", "upskilling hours"],
  }),
  m({
    key: "training_coverage_pct",
    name: "Training coverage (%)",
    description: "Employees who received at least one training / total employees.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "training",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["training coverage", "employees trained"],
  }),
  m({
    key: "training_hours_per_employee",
    name: "Training hours per employee",
    description: "Total training hours / total employees.",
    canonical_unit: "hours_per_employee",
    allowed_units: ["hours_per_employee"],
    category: "social",
    subcategory: "training",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["avg training hours", "per capita training"],
  }),
];

const HEALTH_SAFETY: CanonicalMetric[] = [
  m({
    key: "ltifr",
    name: "Lost Time Injury Frequency Rate",
    description: "LTIs x 1,000,000 / man-hours worked.",
    canonical_unit: "per_million_hours",
    allowed_units: ["per_million_hours", "per_200k_hours"],
    category: "social",
    subcategory: "health_safety",
    dimensions: ["period", "scope_node", "employment_type"],
    aggregation_rule: "ratio",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["lost time injury", "ltifr", "lti rate"],
  }),
  m({
    key: "trifr",
    name: "Total Recordable Injury Frequency Rate",
    description: "TRIs x 1,000,000 / man-hours worked.",
    canonical_unit: "per_million_hours",
    allowed_units: ["per_million_hours", "per_200k_hours"],
    category: "social",
    subcategory: "health_safety",
    dimensions: ["period", "scope_node", "employment_type"],
    aggregation_rule: "ratio",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["total recordable injury rate", "trifr"],
  }),
  m({
    key: "fatality_count_employees",
    name: "Fatalities - employees",
    description: "Work-related fatalities of employees.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "health_safety",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["employee fatalities", "deaths at work employees"],
  }),
  m({
    key: "fatality_count_contractors",
    name: "Fatalities - contractors",
    description: "Work-related fatalities of contractor workers.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "health_safety",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["contractor fatalities", "deaths at work contractors"],
  }),
  m({
    key: "near_miss_count",
    name: "Near miss incidents",
    description: "Near miss incidents reported.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "health_safety",
    dimensions: ["period", "scope_node", "facility"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["near miss", "close call"],
  }),
  m({
    key: "occupational_disease_cases",
    name: "Occupational disease cases",
    description: "Cases of work-related illness identified during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "health_safety",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["occupational illness", "work related disease"],
  }),
  m({
    key: "safety_training_coverage_pct",
    name: "Safety training coverage (%)",
    description: "Employees + contractors who received safety training / total workforce.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "health_safety",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["safety training coverage"],
  }),
];

const HUMAN_RIGHTS: CanonicalMetric[] = [
  m({
    key: "human_rights_training_pct",
    name: "Human rights training coverage (%)",
    description: "Employees trained on human rights / total.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "human_rights",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["human rights training", "hr training"],
  }),
  m({
    key: "human_rights_complaints_received",
    name: "Human rights complaints received",
    description: "Complaints alleging human rights violations received.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "human_rights",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["human rights complaints", "hr complaints"],
  }),
  m({
    key: "human_rights_complaints_resolved",
    name: "Human rights complaints resolved",
    description: "Human rights complaints closed/resolved during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "human_rights",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["complaints resolved"],
  }),
  m({
    key: "child_labour_incidents",
    name: "Child labour incidents",
    description: "Confirmed incidents of child labour in operations or supply chain.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "human_rights",
    dimensions: ["period", "scope_node", "supplier_tier"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["child labour", "child labor incidents"],
  }),
  m({
    key: "forced_labour_incidents",
    name: "Forced labour incidents",
    description: "Confirmed incidents of forced or compulsory labour.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "human_rights",
    dimensions: ["period", "scope_node", "supplier_tier"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["forced labour", "modern slavery"],
  }),
  m({
    key: "discrimination_complaints",
    name: "Discrimination complaints",
    description: "Complaints of workplace discrimination received.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "human_rights",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["discrimination cases", "harassment complaints"],
  }),
];

const COMMUNITY: CanonicalMetric[] = [
  m({
    key: "csr_spend_inr",
    name: "CSR expenditure",
    description: "CSR spend as per Section 135 of Companies Act 2013.",
    canonical_unit: "inr",
    allowed_units: ["inr", "inr_lakh", "inr_crore"],
    category: "social",
    subcategory: "community",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["csr spend", "csr expenditure", "section 135 spend"],
  }),
  m({
    key: "csr_beneficiaries_count",
    name: "CSR beneficiaries",
    description: "Number of beneficiaries directly impacted by CSR programmes.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "community",
    dimensions: ["period", "scope_node", "ses_category"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["csr beneficiaries", "lives impacted"],
  }),
  m({
    key: "local_communities_engaged",
    name: "Local communities engaged",
    description: "Number of distinct local communities engaged via formal mechanisms.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "community",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["communities engaged"],
  }),
  m({
    key: "displacement_count",
    name: "People displaced",
    description: "People displaced by operations during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "community",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["resettlement", "displaced persons"],
  }),
];

const CUSTOMER: CanonicalMetric[] = [
  m({
    key: "customer_complaints_received",
    name: "Customer complaints received",
    description: "Complaints received from customers / consumers.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "customer",
    dimensions: ["period", "scope_node", "channel"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["customer complaints", "consumer complaints"],
  }),
  m({
    key: "customer_complaints_resolved",
    name: "Customer complaints resolved",
    description: "Customer complaints resolved during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "customer",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["complaints resolved"],
  }),
  m({
    key: "product_recall_count",
    name: "Product recalls",
    description: "Number of product recall events during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "customer",
    dimensions: ["period", "scope_node", "product_line"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["product recalls", "voluntary recall"],
  }),
  m({
    key: "customer_satisfaction_score",
    name: "Customer satisfaction (CSAT)",
    description: "Customer satisfaction score (0-100).",
    canonical_unit: "score",
    allowed_units: ["score", "pct", "nps"],
    category: "social",
    subcategory: "customer",
    dimensions: ["period", "scope_node", "channel"],
    aggregation_rule: "weighted_avg",
    data_quality_tier: 2,
    value_constraints: { min: 0, max: 100, dtype: "float" },
    aliases: ["csat", "customer satisfaction"],
  }),
  m({
    key: "data_breach_count",
    name: "Data breach incidents",
    description: "Personal data breach incidents during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "customer",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["data breaches", "privacy incidents"],
  }),
  m({
    key: "data_subjects_affected",
    name: "Data subjects affected by breaches",
    description: "Number of distinct individuals affected by data breach incidents.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "customer",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["users affected", "customers affected by breach"],
  }),
  m({
    key: "parental_leave_taken",
    name: "Parental leave taken",
    description: "Employees who took parental leave during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["parental leave", "maternity leave", "paternity leave"],
  }),
  m({
    key: "parental_leave_return_rate_pct",
    name: "Parental leave return rate (%)",
    description: "Employees returning to work after parental leave / those taking leave.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node", "gender"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["return to work rate"],
  }),
  m({
    key: "collective_bargaining_coverage_pct",
    name: "Collective bargaining coverage (%)",
    description: "Employees covered by collective bargaining agreements / total.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "workforce",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["union coverage", "cba coverage"],
  }),
  m({
    key: "supplier_local_pct",
    name: "Local supplier share (%)",
    description: "Percentage of procurement spend with locally based suppliers (MSME / district).",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "social",
    subcategory: "supply_chain",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["local sourcing", "msme spend share"],
  }),
  m({
    key: "supplier_assessed_count",
    name: "Suppliers assessed (ESG)",
    description: "Number of suppliers assessed on ESG criteria during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "social",
    subcategory: "supply_chain",
    dimensions: ["period", "scope_node", "supplier_tier"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["suppliers screened", "vendors audited"],
  }),
];

// ---------------------------------------------------------------------------
// GOVERNANCE
// ---------------------------------------------------------------------------

const BOARD: CanonicalMetric[] = [
  m({
    key: "board_size",
    name: "Board size",
    description: "Number of directors on the board.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["board size", "directors count"],
  }),
  m({
    key: "independent_directors_count",
    name: "Independent directors",
    description: "Number of independent directors on the board.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["independent directors", "non executive independent"],
  }),
  m({
    key: "women_directors_count",
    name: "Women directors",
    description: "Number of women on the board.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["women directors", "female directors"],
  }),
  m({
    key: "board_meetings_count",
    name: "Board meetings held",
    description: "Number of board meetings convened in the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["board meetings", "directors meetings"],
  }),
  m({
    key: "board_attendance_pct",
    name: "Board meeting attendance (%)",
    description: "Average attendance at board meetings.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "ratio",
    data_quality_tier: 1,
    value_constraints: PERCENTAGE,
    aliases: ["board attendance"],
  }),
  m({
    key: "ceo_chair_separation_bool",
    name: "CEO and Chair are separate",
    description: "True if the CEO and the Board Chair are distinct individuals.",
    canonical_unit: "bool",
    allowed_units: ["bool"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "bool_any",
    data_quality_tier: 1,
    value_constraints: BOOLEAN,
    aliases: ["ceo chair separation"],
  }),
];

const ETHICS: CanonicalMetric[] = [
  m({
    key: "anticorruption_training_pct",
    name: "Anti-corruption training coverage (%)",
    description: "Employees trained on anti-corruption / total.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "governance",
    subcategory: "ethics",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "ratio",
    data_quality_tier: 2,
    value_constraints: PERCENTAGE,
    aliases: ["anti corruption training", "anti bribery training"],
  }),
  m({
    key: "whistleblower_cases_count",
    name: "Whistleblower cases",
    description: "Cases received via whistleblower / vigil mechanism.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "ethics",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["whistleblower complaints", "vigil cases"],
  }),
  m({
    key: "corruption_cases_disciplinary",
    name: "Corruption cases - disciplinary action",
    description: "Cases of corruption resulting in disciplinary action.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "ethics",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["bribery cases", "fraud cases"],
  }),
  m({
    key: "political_contributions_inr",
    name: "Political contributions",
    description: "Total political contributions made during the period.",
    canonical_unit: "inr",
    allowed_units: ["inr", "inr_lakh", "inr_crore"],
    category: "governance",
    subcategory: "ethics",
    dimensions: ["period"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["political contributions", "electoral contributions"],
  }),
];

const RISK: CanonicalMetric[] = [
  m({
    key: "enterprise_risks_count",
    name: "Enterprise risks identified",
    description: "Distinct enterprise risks in the register.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "risk",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["risk register size"],
  }),
  m({
    key: "climate_risks_identified_count",
    name: "Climate risks identified",
    description: "Distinct climate-related risks identified per TCFD methodology.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "risk",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["climate risks", "tcfd risks"],
  }),
  m({
    key: "tcfd_scenarios_used",
    name: "TCFD scenarios used",
    description: "Number of climate scenarios used in scenario analysis.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "risk",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 2,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["climate scenarios"],
  }),
];

const TAX: CanonicalMetric[] = [
  m({
    key: "effective_tax_rate_pct",
    name: "Effective tax rate (%)",
    description: "Income tax / PBT.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "governance",
    subcategory: "tax",
    dimensions: ["period"],
    aggregation_rule: "ratio",
    data_quality_tier: 1,
    value_constraints: { min: -100, max: 100, dtype: "float" },
    aliases: ["etr", "effective tax rate"],
  }),
  m({
    key: "tax_paid_inr_by_country",
    name: "Tax paid by country",
    description: "Cash taxes paid by jurisdiction.",
    canonical_unit: "inr",
    allowed_units: ["inr", "inr_lakh", "inr_crore", "usd"],
    category: "governance",
    subcategory: "tax",
    dimensions: ["period", "country"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["tax paid", "country by country tax"],
  }),
];

const COMPLIANCE: CanonicalMetric[] = [
  m({
    key: "regulatory_actions_count",
    name: "Regulatory actions",
    description: "Distinct regulatory enforcement actions during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "compliance",
    dimensions: ["period", "scope_node", "country"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["regulatory actions", "show cause notices"],
  }),
  m({
    key: "fines_paid_inr",
    name: "Fines & penalties paid",
    description: "Monetary value of fines and penalties paid.",
    canonical_unit: "inr",
    allowed_units: ["inr", "inr_lakh", "inr_crore"],
    category: "governance",
    subcategory: "compliance",
    dimensions: ["period", "scope_node", "country"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["fines paid", "penalties", "monetary sanctions"],
  }),
  m({
    key: "environmental_violations",
    name: "Environmental violations",
    description: "Confirmed environmental violations during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "compliance",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["environment violations", "notices from pcb"],
  }),
  m({
    key: "data_privacy_violations",
    name: "Data privacy violations",
    description: "Confirmed data protection / privacy law violations during the period.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "compliance",
    dimensions: ["period", "scope_node", "country"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["dpdp violations", "gdpr violations"],
  }),
  m({
    key: "ml_models_in_production",
    name: "ML models in production",
    description: "Number of ML/AI models actively serving production decisions (for AI governance disclosures).",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "ai_governance",
    dimensions: ["period", "scope_node"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["ai models", "production models"],
  }),
  m({
    key: "board_committee_count",
    name: "Board committees",
    description: "Number of board committees (audit, NRC, stakeholder relationship, CSR, risk management).",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["board committees", "committees of the board"],
  }),
  m({
    key: "esg_committee_exists_bool",
    name: "ESG / sustainability committee exists",
    description: "Whether a board or management committee is responsible for ESG / sustainability oversight.",
    canonical_unit: "bool",
    allowed_units: ["bool"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "bool_any",
    data_quality_tier: 1,
    value_constraints: BOOLEAN,
    aliases: ["esg committee", "sustainability committee"],
  }),
  m({
    key: "director_independence_pct",
    name: "Board independence (%)",
    description: "Independent directors / total directors x 100.",
    canonical_unit: "pct",
    allowed_units: ["pct"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "ratio",
    data_quality_tier: 1,
    value_constraints: PERCENTAGE,
    aliases: ["board independence"],
  }),
  m({
    key: "ceo_tenure_years",
    name: "CEO tenure",
    description: "Years the current CEO has been in role.",
    canonical_unit: "years",
    allowed_units: ["years"],
    category: "governance",
    subcategory: "board",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_FLOAT,
    aliases: ["ceo tenure"],
  }),
  m({
    key: "external_audit_qualifications",
    name: "External audit qualifications",
    description: "Number of qualifications, adverse remarks or disclaimers raised by the external auditor on the financial statements.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "ethics",
    dimensions: ["period"],
    aggregation_rule: "sum",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["audit qualifications", "auditor remarks"],
  }),
  m({
    key: "transition_plan_adopted_bool",
    name: "Climate transition plan adopted",
    description: "Whether a formal climate transition plan has been adopted by the board.",
    canonical_unit: "bool",
    allowed_units: ["bool"],
    category: "governance",
    subcategory: "risk",
    dimensions: ["period"],
    aggregation_rule: "bool_any",
    data_quality_tier: 1,
    value_constraints: BOOLEAN,
    aliases: ["transition plan", "net zero plan"],
  }),
  m({
    key: "scope3_screened_categories_count",
    name: "Scope 3 categories screened",
    description: "Number of GHG Protocol Scope 3 categories the entity has screened for materiality (0-15).",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "risk",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: { min: 0, max: 15, dtype: "int" },
    aliases: ["scope 3 screening"],
  }),
  m({
    key: "esg_targets_count",
    name: "ESG targets set",
    description: "Number of publicly disclosed ESG targets currently being tracked.",
    canonical_unit: "count",
    allowed_units: ["count"],
    category: "governance",
    subcategory: "risk",
    dimensions: ["period"],
    aggregation_rule: "last",
    data_quality_tier: 1,
    value_constraints: NON_NEGATIVE_INT,
    aliases: ["esg targets"],
  }),
];

// ---------------------------------------------------------------------------
// Build registry
// ---------------------------------------------------------------------------

const ALL: CanonicalMetric[] = [
  ...ENERGY,
  ...WATER,
  ...WASTE,
  ...GHG,
  ...SCOPE3,
  ...GHG_INTENSITY,
  ...AIR,
  ...BIODIVERSITY,
  ...MATERIALS,
  ...WORKFORCE,
  ...DIVERSITY,
  ...COMPENSATION,
  ...TRAINING,
  ...HEALTH_SAFETY,
  ...HUMAN_RIGHTS,
  ...COMMUNITY,
  ...CUSTOMER,
  ...BOARD,
  ...ETHICS,
  ...RISK,
  ...TAX,
  ...COMPLIANCE,
];

function buildRegistry(): Record<string, CanonicalMetric> {
  const out: Record<string, CanonicalMetric> = {};
  for (const metric of ALL) {
    if (out[metric.key]) {
      throw new Error(
        `Duplicate canonical metric key: ${metric.key}. Keys must be unique across the registry.`
      );
    }
    out[metric.key] = metric;
  }
  return out;
}

export const CANONICAL_METRICS: Record<string, CanonicalMetric> = buildRegistry();

export const CANONICAL_KEYS = Object.keys(CANONICAL_METRICS) as readonly string[];

export function getCanonicalMetric(key: string): CanonicalMetric | undefined {
  return CANONICAL_METRICS[key];
}

export function listMetricsByCategory(category: MetricCategory): CanonicalMetric[] {
  return Object.values(CANONICAL_METRICS).filter((x) => x.category === category);
}

export function listMetricsBySubcategory(subcategory: string): CanonicalMetric[] {
  return Object.values(CANONICAL_METRICS).filter((x) => x.subcategory === subcategory);
}
