"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PageHeader } from "@/components/common/page-header";
import { useTenant } from "@/lib/api/queries";
import { toast } from "sonner";

export default function BrandingPage() {
  const { data: t } = useTenant();
  const [color, setColor] = useState(t?.primaryColor ?? "#047857");
  const [name, setName] = useState(t?.name ?? "Imagine Powertree Group");

  return (
    <div className="p-6 space-y-5 max-w-4xl">
      <PageHeader title="Branding" description="Customize your tenant's appearance, report cover and email templates" actions={<Button size="sm" onClick={() => toast.success("Saved")}>Save</Button>} />

      <Card>
        <CardHeader><CardTitle>Identity</CardTitle></CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2">
          <div>
            <Label>Tenant Name</Label>
            <Input className="mt-1.5" value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div>
            <Label>Primary Color</Label>
            <div className="mt-1.5 flex items-center gap-2">
              <input type="color" value={color} onChange={(e) => setColor(e.target.value)} className="h-10 w-12 cursor-pointer rounded-lg border border-slate-200" />
              <Input value={color} onChange={(e) => setColor(e.target.value)} className="font-mono" />
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader><CardTitle>Report Cover Preview</CardTitle></CardHeader>
        <CardContent>
          <div className="aspect-[1/1.2] max-w-md rounded-xl p-8 text-white shadow-elevated" style={{ background: `linear-gradient(135deg, ${color} 0%, ${color}cc 100%)` }}>
            <div className="text-[10px] uppercase tracking-widest opacity-70">BRSR · BRSR Core</div>
            <h1 className="mt-3 text-3xl font-bold">Business Responsibility & Sustainability Report</h1>
            <div className="mt-2 text-sm opacity-90">{name}</div>
            <div className="mt-32 text-xs opacity-80">FY24-25 · Generated by BRSR AI</div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
