---
apiVersion: v1
kind: Namespace
metadata:
  name: brsr-app
  labels:
    name: brsr-app
    tier: application
    linkerd.io/inject: enabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: brsr-ai
  labels:
    name: brsr-ai
    tier: ai
    linkerd.io/inject: enabled
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: brsr-data
  labels:
    name: brsr-data
    tier: data
    linkerd.io/inject: enabled
    pod-security.kubernetes.io/enforce: baseline   # data services occasionally need extra caps
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    tier: platform
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    name: ingress
    tier: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    tier: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
    tier: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
  labels:
    name: karpenter
    tier: platform
